using MyProject.Application;
using MyProject.Application.Models;

namespace MyProject.API;

public class HuffmanQuery
{
    /// <summary>
    /// This method was generated by a human
    /// </summary>
    /// <param name="input"></param>
    [GraphQLName("getHuffmanEncoding")]
    public GetHuffmanEncodingResponse _GetHuffmanEncoding(string input)
    {
        return new GetHuffmanEncodingResponse(input, HuffmanEncoder.EncodeString(input));
    }

    /// <summary>
    /// This method was written by AI
    /// </summary>
    /// <param name="input"></param>
    public static GetHuffmanEncodingResponse GetHuffmanEncoding(string input)
    {
        try
        {
            // Call the static method directly
            var huffmanCodes = HuffmanEncoder.EncodeString(input);

            return new GetHuffmanEncodingResponse(input, huffmanCodes);
        }
        catch (Exception ex)
        {
            // Handle any exceptions (e.g., invalid input, encoding errors, etc.)
            throw new InvalidOperationException($"Error getting Huffman encoding: {ex.Message}");
        }
    }
}

public record GetHuffmanEncodingResponse(
    string InputString,
    ICollection<HuffmanCode> HuffmanCodes);


